apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../deploy

patches:
- patch: |-
    # Ensure the controller is scheduled on worker nodes, not the control plane.
    - op: add
      path: /spec/template/spec/affinity
      value:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
    # Add image pull secrets for Private Google Container Registry access.
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: gcr-json-key
  target:
    kind: Deployment
    name: tpu-node-group-controller-manager

images:
- name: CONTROLLER_IMAGE
  newName: IMAGE_PLACEHOLDER
  newTag: TAG_PLACEHOLDER
